name = "Douglas Hanley"

pdf_link = "hanley_cv.pdf"
pdf_icon = "mini_print.svg"

info_label = "Personal Information"
address = [
	"230 S. Bouquet St.",
	"4507 W. W. Posvar Hall",
	"Pittsburgh, PA 15260",
]
contact = [
	"<a href=\"mailto:doughanley@pitt.edu\">doughanley@pitt.edu</a>",
	"<a href=\"http://doughanley.com/\">doughanley.com</a>",
	"(330) 536-3277",
]

[[blocks]]
title = "Employment"
rows = [
	"Assistant Professor, Department of Economics, University of Pittsburgh, 2014-Present",
	"Visiting Scholar, Federal Reserve Bank of St. Louis, 2017 (short term)",
]

[[blocks]]
title = "Education"
rows = [
	"Ph.D., Economics, University of Pennsylvania, 2014",
	"B.S., Economics, California Institute of Technology, 2006",
]

[[blocks]]
title = "Research Interests"
rows = [
	"Macroeconomics, Knowledge Diffusion, Technological Change, Computational Methods, Climate Economics",
]

[[blocks]]
title = "Publications"
rows = [
	"Optimal Taxation and R&D Policies (with Ufuk Akcigit and Stefanie Stantcheva), <i>Econometrica</i>, 2022",
	"High-speed Rail and Collaborative Innovation (with Mingqin Wu), <i>Regional Science and Urban Economics</i>, 2021",
	"Back to Basics: Basic Research Spillovers, Innovation Policy and Growth (with Ufuk Akcigit and Nicolas Serrano-Velarde), <i>Review of Economic Studies</i>, 2020 <br/> Cited in the <a href=\"https://www.gpo.gov/fdsys/pkg/ERP-2016/pdf/ERP-2016.pdf\">Economic Report of the President 2016</a>",
	"Assessing the Rate of Replication in Economics (with James Berry, Lucas Coffman, Rania Gihleb, and Alistair Wilson), <i>American Economic Review (Papers and Proceedings)</i>, 2017",
	"Transition to Clean Technology (with Daron Acemoglu, Ufuk Akcigit, and William Kerr), <i>Journal of Political of Economy</i>, 2016",
]

[[blocks]]
title = "Working Papers"
rows = [
	"Science is Shaped by Wikipedia: Evidence from a Randomized Control Trial (with Neil Thompson)",
	"From Patents to Products: Innovation, Product Creation, and Firm Growth (with David Argente, Salomé Baslandze, and Sara Moreira)",
	"Economics and Epidemics: Evidence from an Estimated Spatial Econ-SIR Model (with Mark Bognanni, Daniel Kolliner, and Kurt Mitman)",
	"Innovation and Patent Policy with Interdependent Technology",
]

[[blocks]]
title = "Research in Progress"
rows = [
	"Unleashing the Dragon: The Case for Patent Reform in China (with Lee Branstetter and Huiyan Zhang)",
	"Spatial Clustering of Firms: A Machine Learning Approach (with Chengying Luo and Mingqin Wu)",
	"Theory and Evidence on the Relationship Between Corruption and Innovation (with Mingqin Wu)",
	"International Competition in the Race to Clean Technology (with Chengying Luo)",
	"Yellow Fever and the Growth of American Cities (with Sean McCoy and Werner Troesken)",
]

[[blocks]]
title = "Teaching"
rows = [
	"Graduate: Computational Methods in Economics, Advanced Economic Growth, Advanced Macroeconomic Theory I/II",
	"Undergraduate: Macroeconomics Proseminar, Economic Growth Elective, Intermediate Macroeconomics, Intermediate Microeconomics (Penn)",
]

[[blocks]]
title = "Seminars"
rows = [
	"2019: Federal Reserve Bank of Cleveland, Seoul National University, South China Normal University (Guangzhou)",
	"2018: World Bank, Einaudi Institute for Economics and Finance (Rome), South China Normal University (Guangzhou)",
	"2017: Seoul National University",
	"2015: U of Hong Kong, Sogang U (Seoul), IIES (Stockholm)",
	"2014: U of Toronto, USC (Marshall), U of Pittsburgh, U of North Carolina (Chapel Hill), CREI (Barcelona)",
]

[[blocks]]
title = "Conferences"
rows = [
	"2021: Taiwan Symposium on Innovation Economics and Entrepreneurship (National Tsing Hua University)",
	"2019: SED Annual Meeting (St. Louis), Korea Economic Review International Conference (Seoul), Econometrics Society China (Jinan University, Guangzhou), Roundtable for Engineering Entrepreneurship Research (Georgia Tech, discussant)",
	"2018: Computational Social Sciences Retreat (Pitt), Econometrics Society Asia Meetings (Seoul), 4th Workshop on Chinese Politics and Society (Shanghai)",
	"2017: Workshop on Innovation and Entrepreneurship (ISET-TSU, Tbilisi), Carnegie-Rochester-NYU Conference on Public Policy (CMU, discussant)",
	"2016: Chinese Economists Society China Meeting(PHBS, Shenzhen)",
	"2015: Firm and Technology Dynamics: A Global Perspective (Nottingham), Barcelona GSE Summer Forum, SED Annual Meeting (Warsaw), Mini Conference on Economic Growth (Chicago)",
	"2010-2013: Penn Money Macro Workshop, SED Annual Meeting, Midwest Macroeconomic Meetings, Penn Money Macro Club, International Industrial Organization Conference",
]

[[blocks]]
title = "Students Supervized"
rows = [
	"Ying-Kai Huang (Ph.D. 2021): Applied Research Scientist - Economist, Snap Inc",
]

[[blocks]]
title = "Thesis Committees"
rows = [
	"Domonkos Vamossy (Ph.D. 2020): Economist, Amazon Web Services",
	"Tianyi Wang (Ph.D. 2020): Postdoctoral Research Associate, Princeton",
	"Jiyeon Kim (Ph.D. 2020): Economist, Korea Development Institute",
	"Chengying Luo (Ph.D. 2019): Senior Data Scientist, Instacart",
	"Hao Feng (Ph.D. 2018): Assistant Professor, Shanghai University of International Business and Economics",
	"Richard Svoboda (Ph.D. 2017): Senior Economist, Amazon",
]

[[blocks]]
title = "Refereeing Service"
rows = [
	"American Economic Review, Econometrica, Review of Economic Studies, Journal of Political Economy, Journal of Monetary Economics, European Economic Review, American Economic Journal: Macroeconomics, Journal of Public Economics, International Economic Review, Macroeconomic Dynamics, Review of Economic Dynamics, Journal of Comparative Economics, Journal of the European Economic Association, Journal of Mathematical Economics, Journal of Development Economics, Review of Economics and Statistics, Journal of Economic Theory, RAND Journal of Economics, The Economic Journal",
]

[[blocks]]
title = "Departmental Service"
rows = [
	"Hiring: Sustainability (Junior and Postdoc, 2015-16), International Trade (Junior, 2016-17), Development (Junior, 2016-17), International Macro (Junior, 2018-19), Econometrics (Junior, 2019-20)",
	"Committees: Website Committee (2016-2020), Department Chair Selection Committee (2021), Diversity Committee (2021), Graduate Admissions Committee (2022)",
]

[[blocks]]
title = "Other Employment"
rows = [
	"Research Assistant, MIT, 2010-2013<br/>Research Assistant, Caltech, 2005-2006<br/>Research Assistant, CITA, Summer 2004<br/>Software Developer, Cyplex Inc, 2006-2007<br/>Software Developer, Lycoris Corp, Summer 2003<br/>Software Developer, KDE Group, 2001-2002",
]
